In [10]:
import torch, numpy as np
import torch.nn as nn

In [3]:
list_a = [1,2,3,4]
tensor_a = torch.tensor(list_a)


tensor([1, 2, 3, 4])


In [4]:
print(tensor_a)

tensor([1, 2, 3, 4])


In [5]:
print(tensor_a.device)

cpu


In [6]:
print(tensor_a.dtype)

torch.int64


In [8]:
array_a = np.array([[1, 1, 1],
       [2, 3, 4],
       [4, 5, 6]])
array_b = np.array([[7, 5, 4],
       [2, 2, 8],
       [6, 3, 8]])

In [9]:
# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a-tensor_b 

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]])


### Creating your first neural network

In [11]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

model = nn.Sequential(
    nn.Linear(8, 4), 
    nn.Linear(4, 1)
)
output = model(input_tensor)

``` html
Input size  = 8
hidden layer 1 = 4 
output layer = 1

8 inputs are connected to the 4 hidden layers so the number of weights will be 8 * 4 
biases for the hidden layer is 4 

so we can generalise the number of parameters of the hidden layer as ((previous layer size + 1) * hidden layer size) ```

In [12]:
output

tensor([[2.1044]], grad_fn=<AddmmBackward0>)

### Activation functions

#### Sigmoid

In [14]:
input_tensor = torch.Tensor([[0.8]])

sigmoid = nn.Sigmoid()

probability = sigmoid(input_tensor)

print(probability)

tensor([[0.6900]])


#### Softmax

In [15]:
input_tensor = torch.Tensor([[0.2, 0.6, 0.1]])

softmax = nn.Softmax(dim=-1)

probability = softmax(input_tensor)

print(probability)

tensor([[0.2944, 0.4392, 0.2664]])


- [] What does the dim -1 represent in softmax