In [7]:
import torch 
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

### Building a binary classifier in PyTorch
Recall that a small neural network with a single linear layer followed by a sigmoid function is a binary classifier. It acts just like a logistic regression.

In this exercise, you'll practice building this small network and interpreting the output of the classifier.

The torch package and the torch.nn package have already been imported for you.

In [2]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8,1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.2240]], grad_fn=<SigmoidBackward0>)


#### Multi class classifier

In [ ]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

### Creating one-hot encoded labels
One-hot encoding is a technique that turns a single integer label into a vector of N elements, where N is the number of classes in your dataset. This vector only contains zeros and ones. In this exercise, you'll create the one-hot encoded vector of the label y provided.

In [8]:
y = 1 
num_classes = 3

one_hot_numpy = np.array([0,1,0])

one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes=3)

In [9]:
one_hot_pytorch

tensor([0, 1, 0])

In [10]:
y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function
criterion = nn.CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor(8.0619, dtype=torch.float64)


- [] Why I need to double the scores for cross entropy

### Accessing the model parameters

In [12]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Sigmoid(),
                      nn.Linear(8, 2))

# Access the weight of the first linear layer
weight_0 = model[0].weight

# Access the bias of the second linear layer
bias_1 = model[2].bias

### Updating the weights manually

In [21]:
model = nn.Sequential(
  nn.Linear(in_features=16, out_features=8, bias=True),
  nn.Linear(in_features=8, out_features=4, bias=True),
  nn.Linear(in_features=4, out_features=2, bias=True)
)

In [19]:
lr = 0.001

In [24]:
nn.init.uniform_(model[0].weight)
nn.init.uniform_(model[1].weight)
nn.init.uniform_(model[2].weight)
nn.init.uniform_(model[0].bias)
nn.init.uniform_(model[1].bias)
nn.init.uniform_(model[2].bias)

Parameter containing:
tensor([0.5108, 0.3449], requires_grad=True)

In [26]:
weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

In [29]:
weight0.grad

In [ ]:
grads0 = weight0.grad
grads1 = weight1.grad
grads2 = weight2.grad

In [30]:
weight0 = weight0 - lr * grads0
weight1 = weight1 - lr * grads1
weights2 = weight2 - lr * grads2

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

### Using the MSELoss
Recall that we can't use cross-entropy loss for regression problems. The mean squared error loss (MSELoss) is a common loss function for regression problems. In this exercise, you will practice calculating and observing the loss using NumPy as well as its PyTorch implementation.

In [22]:
y_hat = np.array(10)
y = np.array(1)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y_hat - y)**2)

# Create the MSELoss function
criterion = nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_hat).float(), torch.tensor(y).float())
print(mse_pytorch)

tensor(81.)
